#properties
#sample #1
querySamples:
  reference-set-1: GRCh37
  position-1: 179832996
  chromosome-1: 1
  alternate-bases-1: 
  dataset-ids-1: 
#sample #2
  reference-set-2: GRCh37
  position-2: 179832996
  chromosome-2: 1
  alternate-bases-2: 
  dataset-ids-2: EGAD00001000741,EGAD00001000740
#sample #3
  reference-set-3: GRCh37
  position-3: 179832996
  chromosome-3: 1
  alternate-bases-3: A
  dataset-ids-3: 
